[package]
name = "twitter_rust"
version = "0.1.0"
authors = ["surender.lamba <surender.lamba@rakuten.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
